---
title: Pari sanaa asumisesta -- miten yliopisto-opiskelijoiden kirjoittamissa vaihtoraporteissa asetetaan tekstikappaleen topiikki?
author: Kirsi Sandberg & Juho Härme
output:
  pdf_document: 
    toc: true
    number_sections: true
    includes:
        in_header: formatting/preamble.tex
  word_document: 
        reference_docx: tyyliohje.docx
  md_document: default
bibliography: bibliography.bib
csl: formatting/utaltl.csl
---


```{r, echo=FALSE}

library(SataTapaa)

```

This paper explores the various strategies writers use to shift from one topic
to another based on a corpus of  student exchange reports. The main questions
addressed in the study are 1) what linguistic means students use to set a new
topic and 2) how these means could be defined functionally and syntactically.
The data for the study consists of xxx reports from exchange period abroad.
Both qualitative and statistical approaches were adopted in order to capture
the complexities of the phenomenon. The paper descibes 13 separate functional
groups of topic-setting strategies. The statistical analysis conducted on these
groups shows that majority of them  can be drawn from three simple micro-level
variables. This information can be used to develop teaching and writing
practises especially in L2 context but to some degree in L1 also.


Avainsanat: topiikki, kirjoittaminen, korpusmentelmät 

Keywords: topic, writing, corpus-based methods


# Johdanto

`r knit_child('johdanto.Rmd', quiet=T)`

# Tekstikappale ja sen topiikki

`r knit_child('teoriaosa.Rmd', quiet=T)`

# Tutkimusaineisto ja -metodi

`r knit_child('metodista.Rmd', quiet=T)`

# Tulokset

Edellä kuvatun laadullisen analyysin tuloksena 
tutkimusaineiston tekstit
jaoteteltiin  `r length(unique(analysoitu_otanta$group))`
ryhmään, joita osiossa 4.1. luonnehditaan yhden edustavan esimerkin avulla.
Kuten metodin kuvauksen yhteydessä todettiin, tässä kuvatut eri topiikin
asettamistapoja edustavat ryhmät on muodostettu systemaattisesti sijoittamalla
toisaan muistuttavat tapaukset samaan kategoriaan. Ryhmien väliset rajat eivät
luonnollisestikaan ole suoraviivaisia, ja jaottelun olisi voinut tehdä
muillakin tavoilla.
Eri ryhmät ovat lisäksi enemmän
tai vähemmän läheisessä yhteydessä toisiinsa, ja näitä linkkejä
on tässä esitetyssä kuvauksessa pyritty osoittamaan. Vaikka varsinainen
ryhmäjako perustuu laadulliseen samankaltaisuuteen, tulkitaan osiossa
4.2. analyysin tulosta eli itse jaottelua tilastollisin menetelmin.


## Tekstikappaleiden analyysi

`r knit_child('yleiskuva.Rmd', quiet=T)`


## Tilastollinen tarkastelu

`r knit_child('puu.Rmd', quiet=T)`

# Päätelmät

`r knit_child('paatelmia.Rmd', quiet=T)`


