
```{r tietojen_lataus, echo=FALSE}

library("SataTapaa")

test <- list(difs=nrow(subset(ristiin_annotointi,(theme_j == "Asuminen" & theme_k != "Asuminen" | theme_k == "Asuminen" & theme_j != "Asuminen"))),
             sims=nrow(subset(ristiin_annotointi,(theme_j == "Asuminen" & theme_k == "Asuminen"))))

```

Nyt käsillä olevan tutkimuksen aineisto koostuu siis yliopisto-opiskelijoiden
vaihtokokemuksestaan kirjoittamista teksteistä. Tarkka tehtävänanto tekstien laatimiseen
oli annettu erillisissä ohjeissa, joissa opiskelijoita pyydetään kirjoittamaan
"matkakertomus, jossa kuvaillaan ja arvioidaan opiskelua ulkomaisessa
yliopistossa tai harjoittelua ulkomailla". Ohjeet sisältävät kahdeksankohtaisen
listan mahdollisesti käsiteltävistä asioista (mm. *etukäteisjärjestelyt*,
*asuminen* ja *merkityksellisyys*). Listaa kehotetaan tulkitsemaan toteamalla, että
"seuraavat ohjeet eivät ole sitovia, mutta ne on hyvä lukea läpi ennen kirjoittamista".

Tässä käsiteltävä lopullinen tutkimusaineisto kattaa kaikkiaan `r nrow(withindicator)`
opiskelijoiden laatimaa tekstiä, jotka tutkimuksen ensimmäisessä vaiheessa annotoitiin
kappaleittain[^alkup_kpl] siten, että jokaiselle kappaleelle merkittiin
topiikki. Yhteensä kaksikymmentä tekstiä[^tarkm] käsittäneen kokeiluaineiston
perusteella päätettiin keskittyä *asumisesta* kertoviin kappaleisiin siitä
syystä, että asumisesta kirjoitettiin lähes jokaisessa analysoidussa näytetekstissä
ja koska asuminen aiheena havaittiin tavallisesti melko selvärajaiseksi. Koska
tekstit analysoi kaksi eri henkilöä (artikkelin tekijät), näyteaineiston
avulla testattiin myös, kuinka samanlaisia tulkinnat kappaleiden aiheista
olivat. Asumiskappaleiden osalta arvioijien tulkinnat olivat samoja `r test$sims`
tapauksessa `r sum(test$difs,test$sims)`:sta. 
[^alkup_kpl]: Käyttäen kirjoittajien itsensä tekemää  kappaleiden ortografista
erottelua.
[^tarkm]: Tarkista määrä

Kokeiluaineiston jälkeen koko tutkimusaineisto käytiin läpi siten, että
teksteistä etsittiin vain kappaleita, joiden topiikki oli tulkittavissa asumiseksi. 
Kun tämä kaikki tekstit kattava varsinainen annotointiprosessi saatiin
päätökseen, lopulliseksi aineistoksi muodostui  `r nrow(withindicator)`
vähintään yhden asumisesta kertovan kappaleen sisältävää tekstiä. Tekstit ovat
keskimäärin `r round(mean(text_statistics$words))` sanaa pitkiä ja sisältävät
kaiken kaikkiaan keskimäärin `r round(mean(text_statistics$paragraphs))`
kappaletta. Prosessin tuloksena saatu tutkimusaineisto on siis
kohtalaisen kokoinen, ja sitä voidaan mahdollisesti jatkossa käyttää erilaisten
kvantitatiivisten päätelmien pohjana. Nyt käsillä olevaa tutkimusta varten päädyttiin
kuitenkin hyödyntämään aineistoa ennen muuta kvalitatiivisesti. Tätä varten
aineistosta eroteltiin tarkempaa analyysia silmällä pitäen
käsiteltäväksi painotettu satunnaisotanta.[^tarkka_menetelma] 


[^tarkka_menetelma]: Satunnaisotannan tekninen toteutus dokumentoitiin
git-versionhallintaan ja on nähtävillä osoitteessa
https://github.com/hrmJ/100-tapaa-indikoida-topiikkia/blob/6217720ecda456708b4b228e166738602b6b8873/rpackage/inst/extdata/edit_included_data.R#L28
(tarkistettu 8.1.2017) 


Satunnaisotannan painottamisella pyrittiin takaamaan, että analysoitava
otos edustaa mahdollisimman kattavasti koko tutkimusaineistoa
[satunnaisotantaan liittyvistä periaatteista ks. esim. @levshina2015, 8].
Otoksen edustavuuden takaamiseksi kaikki `r nrow(withindicator)` tekstiä kattavaa korpusta
rajattiin ja annotoitiin ensin automaattisesti niin pitkälle kuin mahdollista. 
Tämä prosessi piti sisällään seuraavat vaiheet:

1. Määriteltiin, että kaikista potentiaalisesti asumista indikoivista sanoista
   otetaan mukaan ainoastaan varsinaiset asua-verbin johdokset, koska tämä oli
   selvimmin rajattavissa oleva kategoria. Tarkasteltaessa
   topiikki-indikaattoreita tarkasteltiin siis lopulta sitä, minkälaisissa rakenteissa
   kunkin kappaleen ensimmäinen asua-johdos (kuten verbi *asua* tai substantiivit
   *asuminen*, *asunto*, *asuntoasia*, *asuntomarkkinat*) esiintyi. 
2. Huomio kohdistettiin vain niihin `r nrow(subset(withindicator,sentence_number==1))`
   tapaukseen, joissa asua-johdos sijaitsee ensimmäisessä virkkeessä. (perusteluja)



Koska tutkimuksen tarkoituksena on tarkastella nimenomaan sitä, miten uusi topiikki
esitellään lukijalle, rajattiin varsinai
*(tämän mainitseminen johdannossa)*

Määriteltiin, että kaikista potentiaalisesti asumista indikoivista sanoista
otetaan mukaan ainoastaan varsinaiset asua-verbin johdokset, koska tämä oli
selvimmin rajattavissa oleva kategoria. Tarkasteltaessa
topiikki-indikaattoreita tarkasteltiin siis sitä, minkälaisissa rakenteissa
kunkin kappaleen ensimmäinen asua-johdos (kuten verbi *asua* tai substantiivit
*asuminen*, *asunto*, *asuntoasia*, *asuntomarkkinat*) esiintyi. 


Asumisesta kertovien kappaleiden syntaktisesta rakenteesta saatiin yleiskuva
annotoimalla kappaleet koneellisesti dependenssijäsentimellä [ks.
@haverinen2013tdt]. 



Koneellisesti tuotettu annotointi toimi lähtökohtana, kun
kappaleita ryhdyttiin luokittelemaan eri ryhmiin sen mukaan, miten niissä
indikoitiin asumistopiikkia. Luokittelu tapahtui seuraavien vaiheiden mukaisesti:

1. Määriteltiin, että kaikista potentiaalisesti asumista indikoivista sanoista
   otetaan mukaan ainoastaan varsinaiset asua-verbin johdokset, koska tämä oli
   selvimmin rajattavissa oleva kategoria. Tarkasteltaessa
   topiikki-indikaattoreita tarkasteltiin siis sitä, minkälaisissa rakenteissa
   kunkin kappaleen ensimmäinen asua-johdos (kuten verbi *asua* tai substantiivit
   *asuminen*, *asunto*, *asuntoasia*, *asuntomarkkinat*) esiintyi. 
2. Jokaisesta kategoriasta valittiin tarkasteltavaksi puolet (tai vähintään x)
   Tätä kautta mukaan valikoitui eniten niitä, joita... yms.
   Tämä joukko analysoitiin siten, että mukaan otettiin vain tapaukset, joissa
   tulkintamme mukaan toteutettiin alatopiikin funktiota.
3. Kun jokaisesta syntaktisesta kategoriasta oli saatu kategorian suhteellisen
   koon mukainen (tai suurin mahdollinen) määrä alatopiikkitapauksia, nämä
   analysoitiin tarkemmin ja ryhmiteltiin eri tapauksiksi.


Analyysin varsinaiset tulokset kunkin syntaktisen kategorian osalta on kuvattu
tarkemmin seuraavassa.
