

```{r, echo=FALSE}
library(dplyr)
ex.ids <- c(286, 42, 839, 699, 317, 107, 341,557,272,498,732,807,298)
esim <- setNames(lapply(ex.ids,function(x)MoreInfo(x)),groups.meta$Nimi)
#Järjestetään esimerkit koon mukaan
totals <- sort(sapply(esim,function(x)x$total),dec=T)
esim.ordered <- lapply(names(totals),function(x)esim[[x]])
esim.print <- sapply(esim.ordered,function(x)x$sentence)
#Tulostetaan esimerkit suuruusjärjestyksessä niin, että kukin on nimetty loogisesti
ex.names <- data.frame(group=c("Listamaiset","Selkeät yksittäiseen tapahtumaan keskittyvät narratiivit","asuin paikassa x","pari sanaa asumisesta","Linkki","yleistys","Ennakoivat","ennakoivien ja predikoivien välimaasto","oma kokemus","Yliopisto (maggy) tarjosi","Suurin osa opiskelijoista","Kontrasti","asunnon ja asumisen staattinen kuvailu"),
                       label=c("@ee_lista", "@ee_narratiivi", "@ee_predikaatti", "@ee_parisanaa", "@ee_linkki", "@ee_yleistys", "@ee_ennakoivat", "@ee_valimaasto", "@ee_omakokemus", "@ee_maggytarjosi", "@ee_suurionsa", "@ee_kontrasti", "@ee_staattinen"))
print.labels <- as.character(sapply(names(totals),function(x)ex.names$label[ex.names$group==x]))
print.names <- paste0("(",print.labels,")")

for(idx in c(1:length(esim.ordered))){
    esim.ordered[[idx]]$esimerkki <- paste(print.names[[idx]], esim.print[[idx]])
    esim.ordered[[idx]]$id <- ex.ids[which(names(esim) == esim.ordered[[idx]]$group)]
}

```


Laadullisen analyysin tuloksena päädyttiin melko suureen määrään eri
kategorioita. Jaottelun hienojakoisuudella haluttiin säilyttää intuitio
tiettyjen topiikin asettamistapojen muita suuremmasta samankaltaisuudesta.
Määrittelemämme `r length(esim.ordered)` kategoriaa voitaisiin luonnollisesti
koota myös laajemmiksi ryppäiksi. Yksi ryhmiä vertailemalla esiin nouseva
yhdistävä piirre on kirjoittamisen tutkimuksessa (viite x, y, z) käytetty
jaottelu kirjoittajakeskeisiin, *XXXXkeskeisiin* ja *XXXXkeskeisiin*.
Esittelemmekin erottelemamme topiikin asettamistavat seuraavassa jaoteltuna
löyhästi näiden kolmen kategorian mukaisiin alalukuihin. Esittely tehdään
käyttämällä jokaisesta ryhmästä mallina yhtä kappaleen avaavaa virkettä, jonka
laajempi konteksti on nähtävillä liitteessä 1. 

## Kirjoittajakeskeiset lähestymistavat


Kirjoittajakeskeisiksi on tutkimuskirjallisuudessa kutsuttu... Omassa
aineistossamme tällaisiksi topiikinasettamistavoiksi voidaan luokitella
karkeasti ottaen N ryhmää. Näistä suurin -- ja samalla koko tutkimuksen yleisin
-- kategoria ovat esimerkin @ee_lista kaltaiset tapaukset, joihin jatkossa
viittaamme nimellä *listamaiset*.

(@ee_lista) `r esim.ordered[[1]]$sentence`

Esimerkin @ee_lista topiikki-indikaattorina on *asuntoni*-sana, joka tälle
ryhmälle leimallisesti on lauseen alussa sijaitseva objekti.
Asumiseen tai asuntoon ei ole viitattu edeltävissä kappaleissa, vaan topiikkia
asettava virke on samalla ensimmäinen maininta itse topiikista. 
Informaatiorakenteellisesti tarkasteltuna esimerkin @ee_lista *asuntoni*
voidaan nähdä alatopiikkina (ks. osio x.x edellä),
vaikka esimerkissä @ee_lista ei täyty Dikin [-@dik1989, 275]
 kuvailema ehto siitä, että varsinainen ylätopiikki olisi
erikseen esitelty lukijalle [vrt. myös @guijarro2001, 110]. Kirjoittaja
kuitenkin operoi tässä ja useimmissa muissa ryhmän tapauksissa
niin selkeästi tehtävänannossa ehdotetun rakenteen puitteissa, että hän olettaa
lukijan automaattisesti jakavan käsityksen siitä, mitä  aiheita tekstin
diskurssitopiikkiin, vaihtokokemukseen, liittyvien asioiden joukko pitää
sisällään. Asunto tai asuminen nähdään toisin sanoen lukijan käytettävissä
olevana entiteettinä [vrt. @chafe1987, 29;  @lambrecht1996, 99], mikä
mahdollistaa sen tuomisen tekstiin ilman ennakkomainintoja tai esittelyjä.
Voisi jopa sanoa, että esimerkin @ee_lista kaltaiset tapaukset eivät niinkään
aseta topiikkia, vaan ennemmin käyttävät jo asetetetuksi oletettua topiikkia.

Toiseksi suurimman kirjoittajakeskeisen ryhmän muodostavat
esimerkin @ee_predikaatti kaltaiset tapaukset, joita tutkimusaineistossa on
 `r esim.ordered[[2]]$total` kappaletta. 

(@ee_predikaatti) `r esim.ordered[[2]]$sentence`

Kaikissa tämän ryhmän tapauksista topiikki-indikaattorina on persoonamuotoinen
*asua*-verbi, minkä takia ryhmään viitataankin jatkossa nimityksellä
*asua-verbilliset*. Näiden virkkeiden pääasiallinen sisältö on yleensä
informaatio siitä, missä kirjoittaja on vaihtonsa aikana asunut. Tämän ryhmän
tapaukset ovat edellistä ryhmää selkeämmin nimenomaan johdantoja uuteen
aiheeseen, ja Dikin jaottelun mukaisesti esimerkin @ee_predikaatti lopussa
mainittu *asuntola* muodostaa esittelytopiikin [-@dik1989, 269]. Vastaavat
*asuin paikassa X* -tyyppiset rakenteet ovat siis keinoja esitellä *paikka X*,
josta tällaisella virkkeellä alkava kappale kertoo. Esimerkin @ee_predikaatti
tapauksessa kirjoittaja jatkaa kappalettaan kuvailemalla asuntonsa sisustuksen,
kämppäkaverit ja vuokran suuruuden.

Kolmannen kirjoittajakeskeisen ryhmän virkkeet ovat ajallisesti 
muita monitasoisempia. Nämä tapaukset on ryhmitelty yhteen, koska 
niissä kaikissa pohjustetaan asumisesta kertomista jollakin 
asumista edeltävään aikaan liittyvällä tapahtumalla. Tällä perusteella
nimitämme tämän ryhmän tapauksia *ennakoiviksi*. Ryhmää edustaa esimerkki
@ee_ennakoivat:

(@ee_ennakoivat) `r esim.ordered[[3]]$sentence`

Esimerkissä @ee_ennakoivat asumistopiikin pohjustus tapahtuu luomalla pieni
jännite: jos kerran ensimmäiseksi kuukaudeksi oli löydetty AirBnb-asunto, miten
asumisasia lopullisesti ratkaistiin? Avausvirkkeen jälkeen kappaleessa selviää,
että AirBnb-ratkaisusta muodostuikin lopulta asunto koko vaihdon ajaksi, ja
kappaleen loppuosassa kirjoittaja siirtyy kuvailemaan tarkemmin asunnon
yksityiskohtia. Informaatiorakenteeltaan ryhmä @ee_ennakoivat onkin hyvin
samanlainen kuin edellinen ryhmä: koko kappaleen topiikkina oleva *asunto*
tuodaan tekstiin esittelytopiikkina ensimmäisessä virkkeessä.

Esimerkki @ee_omakokemus kuvaa *oma kokemus*-ryhmäksi nimeämäämme tapausten
joukkoa. Näissä tapauksissa kirjoittaja käsittelee asumista kuvaamalla sitä
omakohtaisena prosessina, jonka onnistumista tai epäonnistumista voidaan
arvioida.

(@ee_omakokemus) `r esim.ordered[[4]]$sentence`

Esimerkissä @ee_omakokemus topiikkia indikoi deverbaalisubstantiivi (tässä *asuminen*),
mikä tähän ryhmään luokitelluilla kaikkiaan `r esim.ordered[[4]]$total` tapauksella onkin
tyypillistä: kenties suoraviivaisin tapa kuvailla omaa kokemusta jostakin
varsinaisen diskurssitopiikin osa-alueesta on niputtaa kokemus nominalisoituun
verbimuotoon ja luonnehtia tätä predikatiivilauseella. Näissä tapauksissa
kuvataan, miten *asunnon hakeminen oli helppoa* tai miten *kaikkein vaikeinta
oli asunnon löytäminen*. Informaatiorakenteen kannalta *oma kokemus* -ryhmän tapaukset ovat
monesti listamaiset-ryhmän tapaan alatopiikkeja. Esimerkki @ee_omakokemus on
kuitenkin esimerkkiä @ee_lista selvemmin topiikkia asettava virke, sillä siinä
asumisen rooli yhtenä vaihtokokemuksen osana on ilmaistu eksplisiittisesti.

Oma kokemus -ryhmää lähellä ovat esimerkin @ee_kontrasti kaltaiset tapaukset, 
joissa niissäkin usein reflektoidaan omien valintojen onnistumista. Esimerkin @ee_kontrasti
edustamalle *kontrastia ilmaisevalle* ryhmässä omaa kokemusta kuitenkin 
verrataan eksplisiittisesti toisten kokemuksiin.

(@ee_kontrasti) `r esim.ordered[[7]]$sentence`

Informaatiorakenteeltaan ryhmän @ee_kontrasti tapaukset ovat nekin tyypillisesti 
alatopiikkeja, ja olettavat indikaattorisanan implikoiman topiikin jossain määrin
esimerkin @ee_lista kaltaisesti jo asetetuksi. 

Laadullisessa analyysissa luokiteltiin omaksi pieneksi ryhmäkseen 
myös esimerkin @ee_valimaasto kaltaiset `r total` tapausta:


(@ee_valimaasto) `r esim.ordered[[12]]$sentence`


Nämä topiikkia asettavat tapaukset sijoittuvat ryhmien @ee_predikaatti,
@ee_ennakoivat ja @ee_narratiivi välimaastoon. Kuten mainituissa ryhmissä,
myös näissä tapauksissa kyseessä on varsinainen aiheeseen johdattava
virke, jossa kappaleen topiikki esitellään uutena avausvirkkeen
loppupuolella. Myös ryhmässä @ee_valimaasto 
kuvataan ajallinen jännite, mutta se esitetään usein eri järjestyksessä
kuin ryhmässä @ee_ennakoivat. Siinä missä esimerkki @ee_ennakoivat
esitti kappaleen alussa avoimen tilanteen ja myöhemmässä kappaleessa tilanteen
ratkaisun, aloittaa esimerkki @ee_valimaasto ratkaisusta (saavuttaessa asunto
oli jo löydetty) ja käyttää lopun kappaleen takaumamaisesti sen kuvailuun,
miten ratkaisuun päästiin (kirjoittaja oli etsinyt asuntoa valmiiksi Facebookin
kautta).


Esimerkin @ee_narratiivi edustamassa ryhmässä asumisesta raportoidaan kertovan
tekstityypin avulla, mikä käy tästä esimerkistä esiin erityisen selvästi, koska
kirjoittaja on käyttänyt ajan ilmausta. 

(@ee_narratiivi) `r esim.ordered[[10]]$sentence`

Aikamuoto ryhmän @ee_narratiivi virkkeissä on tyypillisesti imperfekti.
Näissäkin tapauksissa topiikki-indikaattori on informaatiorakenteen kannalta
esittelytopiikki, joka esimerkin narratiivisuuden vuoksi tulee asetetuksi
muita tässä tarkasteltuja uuden topiikin sisältäviä ryhmiä
implisiittisemmin.  Kaikkiaan ryhmään @ee_narratiivi kuuluu
`r esim.ordered[[10]]$total` tapausta.

## Depersonalisoidut (??) lähestymistavat

Depersonalisoiduilla lähestymistavoilla viitataan... Kirjallisuudessa...

Laadullisen analyysin tuloksena laadituista ryhmistä kenties selkeimmin
kirjoittajan omasta kokemuksesta irtautuvat esimerkin @ee_yleistys
kaltaiset tapaukset, joita nimitämme *yleistäviksi*.

(@ee_yleistys) `r esim.ordered[[8]]$sentence `

Samoin kuin esimerkissä @ee_omakokemus, myös esimerkissä @ee_yleistys
topiikki-indikaattorina on koko lauseen ensimmäisenä sijaitseva
*asuminen*-sana. Erona näiden esimerkkien välillä on, että siinä
missä esimerkki @ee_omakokemus on informaatiorakenteen kannalta 
omasta vaihtokokemuksesta lohkaistu alatopiikki, ankkuroituu esimerkki @ee_yleistys
siihen fyysiseen paikkaan, jossa vaihto tapahtui.
Ryhmän @ee_yleistys kirjoittajat eivät siis niinkään lähde liikkeelle
omista kokemuksistaan, vaan käsittelevät tilannetta laajemmin, tavoitteenaan
eräässä mielessä jakaa maailmantietoa lukijalleen. 

Yleistys kirjoittajan oman kokemuspiirin ulkopuolelle voidaan
kuitenkin tehdä myös toisella tavalla. Esimerkissä
@ee_maggytarjosi ja kahdeksassa muussa tapauksessa tämä tapahtuu 
keskittymällä johonkin ulkoiseen agenttiin, jonka toimet
vaikuttavat kirjoittajaan yleisesti ja asumisen järjestymiseen
erityisesti. 

(@ee_maggytarjosi) `r esim.ordered[[9]]$sentence`

Esimerkissä @ee_maggytarjosi  on informaatiorakenteen kannalta 
katsottuna kyse esimerkkien @ee_predikaatti, @ee_ennakoivat ja @ee_staattinen
tapaan esittelytopiikista, mutta tässä esittely toteutetaan hyödyntämällä
jotakin tekstin kannalta keskeistä ulkoista toimijaa (kuten suurlähetystön
henkilökuntaa), minkä takia tämä tapausjoukko nimettiin *ulkoinen toimija* -ryhmäksi. 
Näitä lähellä ovat esimerkin @ee_suurionsa kaltaiset *suurin osa*-ryhmäksi
nimetyt tapaukset, joissa asumistopiikki esitellään kertomalla jotakin siitä,
miten kirjoittajan kuvaamassa tilanteessa yleensä toimitaan tai miten suurin osa 
toimii:

(@ee_suurionsa) `r esim.ordered[[13]]$sentence`

Suurin osa -ryhmän virkkeet ovat lähellä kontrastiryhmää, johon luetuissa
tapauksissa oleellista on kirjoittajan itsensä vertailu muihin. 
Esimerkin @ee_suurionsa edustamille tapauksissa kirjoittaja ei kuitenkaan
yleensä kuvaa omaa toimintaansa mitenkään yleiselle toimintatavalle vastakkaisena,
vaan useimmiten noudattaa myös itse kuvailemaansa enemmistön mallia.
Virke @ee_suurionsa on todella vain keino johdattaa lukija kappaleen varsinaiseen
aiheeseen, *Ekonom*-nimiseen asuntolaan (esittelytopiikki), jonka sijainnista, vuokratasosta
ja muista ominaisuuksista kappale kertoo. 

Depersonalisoituihin tapauksiin laskettiin myös seuraavan esimerkin kaltaiset 
*staattinen kuvailu* -ryhmäksi luokitellut tapaukset:

(@ee_staattinen) `r esim.ordered[[6]]$sentence`

Esimerkissä @ee_staattinen kirjoittaja esittelee uuden topiikin lähtemällä
liikkeelle konkreettisesti asuntonsa luonnehtimisesta (vrt. esimerkki
@ee_omakokemus, jossa luonnehditaan kirjoittajan kokemusta). Vastaavia
asuntolaa tai asumista staattisesti kuvaavia topiikin asettavia virkkeitä on
kaikkiaan `r total` kappaletta. Informaatiorakenteeltaan nämä tapaukset ovat
monesti lähellä ryhmää @ee_predikaatti, sillä molemmissa kappaleen ensimmäinen
virke esittelee lukijalle sen, minkä yksityiskohtaiseen kuvailuun koko
loppukappale keskittyy. Esimerkissä @ee_staattinen topiikki asetetaan kuitenkin
jossain määrin implisiittisemmin, ja hyppäys edellisestä aiheesta (esimerkin
@ee_staattinen tapauksessa HIV-testin teettäminen) on tyypillisesti rajumpi.
Tämä selittää sitä, että peräti `r otsikkosuhde` ryhmän @ee_staattinen
tapauksista (ei kuitenkaan tässä esitetty esimerkki) sisältää asumiskappaletta
edeltävän väliotsikon.

## Metatason (??) lähestymistavat


Esimerkissä @ee_linkki indikaattorina on *asuntoloista*-sana. Ilman kontekstia
tarkasteltuna tämäkin tapaus vaikuttaa samalta kuin listamainen esimerkki, mutta
laajemman analyysin tuloksena selvisi, että kirjoittaja on jo aiempana,
kirjoittaessaan etukäteisjärjestelyistä ja kohdemaahan saapumisesta, rakentanut
kuvaa paikallisista asuntolavaihtoehdoista ja asuntolassa elämisestä. Tämän
ryhmän tekstit sijoittuvatkin toissijaisesti myös johonkin toiseen alaryhmään,
mutta ovat erottuneet omasta alaryhmästään kontekstin tarkastelun vaiheessa.

(@ee_linkki) `r esim.ordered[[5]]$sentence`


Esimerkin @ee_linkki kaltaisia aiempaan kontekstiin tietoisesti sidottuja
tapauksia on aineistossa `r total` kappaletta. Näissä tapauksissa kyse on 
virketasolla tarkasteltuna joko annetuista topiikeista -- jos
kontekstuaalinen linkki on muodostettu suhteellisen lähellä tässä käsiteltävää
varsinaista asumiskappaletta  -- tai, jos edellinen maininta on selvästi
kauempana, palautetuista topiikeista [@dik1989, 270--271]. X:ssä 
tämän ryhmän virkkeessä kappaletta edeltää väliotsikko.


Oman, selvästi muista erottuvan ryhmänsä muodostavat ne esimerkin @ee_parisanaa
edustamat `r total` tapausta, joissa kirjoittaja
eksplisiittisesti ilmaisee siirtyvänsä käsittelemään asumista.

(@ee_parisanaa) `r esim.ordered[[11]]$sentence`

*Sitten pari sanaa asumisesta* -tyyppisten
johdantovirkkeiden voisi ajatella jossain määrin korvaavan väliotsikoita tekstissä,
vaikka yksi tähän ryhmään luokiteltu virke
(*Monella varmaan herää jo kysymys, entäs asuminen?*) tekeekin poikkeuksen.
Nämä `r total` esimerkkiä edustavat Dikin jaottelussa esittelytopiikkeja [-@dik1989, 268], ja
ovat aiheeseen johdattamisen implisiittisyys--eksplisiittisyys-asteikon
eksplisiittisessä ääripäässä (vrt. päinvastaisessa ääripäässä sijaitseva ryhmä @ee_lista).


## Kokoavasti

Kuten edellä metodin kuvauksen yhteydessä todettiin, tässä kuvatut eri
topiikin asettamistapoja edustavat ryhmät on muodostettu
sijoittamalla aina toisaan muistuttavat tapaukset samaan kategoriaan. Ryhmien
väliset rajat eivät luonnollisestikaan ole suoraviivaisia, ja jaottelun
olisi voinut tehdä muillakin tavoilla. Eri ryhmät ovat lisäksi enemmän
tai vähemmän läheisessä yhteydessä toisiinsa, ja näitä linkkejä
on tässä esitetyssä kuvauksessa pyritty osoittamaan. Seuraavaksi 
nyt esiteltyjen ryhmien rakenteellisia tyyppipiirteitä tutkitaan tarkemmin
määrällisestä näkökulmasta. Argumenttimme on, että vaikka ryhmät on muodostettu
puhtaasti tulkitsemalla eri tekstien välisiä samankaltaisuuksia,
on suurimmalle osalle ryhmistä melko yksinkertaista antaa
myös muodolliset, lähinnä rakenteeseen perustuvat määritelmät,
joiden soveltaminen voi joillekin kirjoittajille tai opettajulle olla abstrakteja
funktionaalisten ominaisuuksien kuvailuja helpompaa.


