This paper explores the various strategies writers use to shift from one
topic to another based on a corpus of student exchange reports. The main
questions addressed in the study are 1) what linguistic means students
use to set a new topic and 2) how these means could be defined
functionally and syntactically. The data for the study consists of xxx
reports from exchange period abroad. Both qualitative and statistical
approaches were adopted in order to capture the complexities of the
phenomenon. The paper descibes 13 separate functional groups of
topic-setting strategies. The statistical analysis conducted on these
groups shows that majority of them can be drawn from three simple
micro-level variables. This information can be used to develop teaching
and writing practises especially in L2 context but to some degree in L1
also.

Avainsanat: topiikki, kirjoittaminen, korpusmentelmät

Keywords: topic, writing, corpus-based methods

Johdanto
========

Opiskelijavaihdosta kirjoitettava vaihtoraportti on institutionaalinen
teksti, jonka kirjoittamiseen yliopisto antaa sisältöpainotteisen
ohjeistuksen. Näillä verkossa julkaistavilla raporteilla on selkeä
funktio: tukea vaihtojaksoa suunnittelevia opiskelijoita päätöksenteossa
ja omaan tulevaan vaihtojaksoonsa valmistautumisessa. Niiden voi katsoa
edustavan samaa tekstilajia (tekstilajin määritelmästä ks. esim.
(Juvonen ym. 2012)) [tähän vielä Suvin määritelmä
mukaan](Swales%201990,%2045-58). Vaihtoraportti, kuten tekstilajit
yleensäkin on dynaaminen ja voi toteutua kielellisesti äärettömän
monella eri tavalla, ja tekstiä, jossa kieltä käytetään varioiden ja
monipuolisesti mutta lajinsa konventioita riittävässä määrin noudatellen
arvostetaan ja pidetään lukijan näkökulmasta luettavana ja
mielenkiintoisena.

Lähestyessämme 2020-lukua Suomen oppilaitoksissa ja korkeakouluissa
opiskelee kasvava joukko kirjoittajia (L1 ja L2), jolla ei opintojensa
alkuvaiheessa ole opinnoissa menestymiseen tarvittavia tekstitaitoja.
Akateemisen kirjoittamisen (laajemmin erikoiskielten) tarkasteluun
liitty usein käsitys, että tekstilajitietoisuus ja -tuntemus edesauttaa
ja laajentaa kielenkäyttäjän kielellistä repertuaaria (Vuorijärvi 2013:
15) ja siinä mainitut lähteet. Sitä, miten oppija pääsee tekstilajin
kautta kiinni kielen rakenteiden varioiviin käyttötapoihin, ei Suomen
kontekstissa ole nähdäksemme tutkittu. Funktionaalisista lähtökohdista
tarkasteltuna esitetty näkemys kaipaisi kuitenkin empiiristä tutkimusta,
koska myös rakenteiden hallinnan on osoitettu olevan kytköksissä tekstin
laatuun (ks. esim. (Jisa & Tochinsky 2009)\]

Nykyisessä funktionaalista kielikäsitystä ja tutkivaa oppimista
korostavassa pedagogisessa kehyksessä tarjolla olevat pääosin
preskriptiiviset ohjeistukset tekstikappaleen rakentumisesta (ks. esim.
xxx) eivät palvele tarkoitustaan. Ns. uusi kirjoittaja on aktiivinen
tiedonhakija ja tekstien tutkija, joka ei enää kysy, miten minun pitäisi
tämä tehdä vaan millä eri tavoilla tämä on tehty. Tällä kirjoittajalla
voi olla nykyisen, tekstilajitietoisen kouluopetuksen pohjalta ymmärrys
tekstilajista, mutta repertuaarissa ei olekaan sopivaa rakennetta, jolla
pystyisi itse tuottamaan tavoitemuotoisen tekstin ja esim. käymään
dialogia lukijansa kanssa (ks. (Juvonen 2014a)).

Viime aikaisessa kirjoittamista käsittelevässä fennistisessä
tutkimuksessa on tarkastelu sitä, miten tekstikokonaisuus rakentuu
funktionaalisten tai retoristen jaksojen pohjalta. On myös tarkennettu
siihen, millaisin kielisin keinoin kirjoittajat toteuttavat tekstin
rakenteen kannalta keskeisiä funktioita tai siirtoja (ks. esim. (Juvonen
2014a)(Komppa 2012)(Paldanius 2017)(Vuorijärvi 2013)). Hierarkkisesti
rakentuneiden tekstien rinnalla eää huomattavan paljon tekstilajeja
(Hiippala 2013)(Komppa 2012)(Vuorijärvi 2013)), joissa tekstin
rakennetta voi kuvata ennemmin topiikkipohjaiseksi ja temaattisen
sisällön pohjalta rakentuvaksi kuin hierarkkisesti. Rakenne muodostuu
sekventiaalisesti tai lineaarisesti peräkkäin asetetuista
sisältötopiikeista, jotka kytkeytyvät tavalla tai toisella
diskurssitopiikkiin. Hierarkkisten tekstirakenteiden rinnalla tekstin
rakentaminen ns. sisältö edellä vaikuttaisikin olevan yhtä lailla
relevantti kirjoitusstrategia myös korkeakoulussa.

Saatavilla olevan tutkimustiedon rinnalle haluammekin selvittää, miten
kirjoittaja voi päästä alkuun kappaleen kirjoittamisessa, jos häntä
ohjaa tieto tekstikappaleen topiikista, ts. siitä mitä kappaleen pitäisi
pitää sisällään. Meitä kiinnostaa, millä tavalla ja mitä rakenteita
käyttäen kirjoittaja asettaa tekstikappaleen sisältötopiikin ja siirtyy
tekstitopiikista toiseen. Analyysin avulla haetaan vastausta seuraaviin
tutkimuskysymyksiin:

1.  Millaisia tapoja yliopisto-opiskelijat käyttävät saman topiikin
    asettamiseen?
2.  Miten näitä tapoja voidaan määritellä toisaalta funktionaalisesti,
    toisaalta syntaktisesti?

Tutkimus toteutetaan korpusvetoisesti yhdistelemällä laadullisia (osio
4.1) ja määrällisiä (osio 4.2) menetelmiä.

Tekstikappale ja sen topiikki
=============================

Tämä tutkimus on soveltava ja jo lähtökohdiltaan tähtää kirjoittamisen
oppimisen ja opettamisen kehittämiseen sekä sovellusmahdollisuuksiin. Se
asettuu erikoiskielten kontekstiin, mutta lähestyy ennemminkin tekstin,
kielen rakenteiden ja leksikon jakamia rajapintoja kuin tekstin
kokonaisuutta tai tekstilajin muodostumista sinänsä. Samasta
lähtökohdasta on myös valittu keskeinen analyysiyksikkö - tekstikappale
- joka on toistaiseksi harvakseltaan ollut tutkimuksen kohteena (ks.
kuitenkin x ja y) mutta jonka kirjoittamiseen ohjeistetaan oppikirjoissa
ja kirjoittamisoppaissa.

Kirjoittajan kannalta kappalejako on hyvin konkreettinen työkalu ja
funktionaalinen kielenyksikkö, vaikka tutkimuksessa niitä lähestytään
lähinnä ortografisina merkkeinä, jotka eivät itsessään ole merkitseviä
tekstin rakentumisen kannalta. Kirjoittamisoppaissa ja ohjeistuksissa
annetaan kuvauksia siitä, millä tavalla teksti rakentuu kappaleistaan,
ja millaisia kappaleiden – sisällön ja funktion tasolla – olisi hyvä
olla (viitteet tähän vielä). Lisäksi kappaleiden koherentti toisiinsa
sitominen on tyypillisesti arviointikriteeri, esim.
ylioppilaskirjoituksissa (viite).

Englanninkielisessä kirjoittamisen opetuksen perinteessä on ollut tapana
käyttää topic sentence -käsitettä kuvaamaan virkettä, jolla kirjoittaja
ilmaisee kappaleen tärkeimmän ajatuksen (ks. esim. Smith 2008). Suomeksi
tämä kääntyy nykyisellään ydinvirkkeeksi, joka yhdessä tukivirkkeiden
kanssa muodostaa kappaleen. Tekstikappaleen ytimen tavoittelun sijaan
kohdistammekin huomiomme siihen, miten kirjoittaja siirtyy tekstissään
aiheesta toiseen. Nimitämme siirtymän toteuttavia virkkeitä *topiikkia
asettaviksi* vrt. (Juvonen 2014b).

Käyttämämme topiikin käsite pohjaa Simon Dikin funktionaalisessa
kieliopissaan (1989) antamaan esitykseen, jota vastaavassa
tekstikappaleiden rakenteen analyysissa on soveltanut mm. Jesus Guijarro
(2001). Dikin mukaan (mts. 266) kaikilla diskursseilla (joka Dikin
määrittelemänä tarkottaa mitä tahansa koherenttia tekstiä) on se
ominaisuus, että ne kertovat jostakin. Tämä ominaisuus, jota nimitämme
*aiheisuudeksi* (*aboutness*), koskee paitsi tekstiä kokonaisuutena,
myös siitä eroteltuja alakokonaisuuksia, kuten kappaleita ja virkkeitä.
Määrittelemmekin topiikin tämän artikkelin puitteissa siksi, mistä
teksti, kappale tai virke kertoo (vrt. Lambrecht 1996: 118).

Tekstin sisällä topiikit muodostavat Dikin (mt. 271, vrt. myös Givón
1983) jaottelussa topiikkiketjuja, joiden katsomme tässä artikkelissa
koostuvan *esittelytopiikeista* (Dikillä *new topic*), *esitellyistä
topiikeista* (Dikillä *given topic*) ja *lohkotopiikeista* (Dikillä
*subtopic*). Esittelytopiikkeja ovat tapaukset, joissa kirjoittaja tuo
jonkin aiheen tekstiin ensimmäistä kertaa ja esiteltyjä topiikkeja taas
sellaiset tapaukset, jotka on jo tuotu aiemmin ja joihin nyt
palataan.Lohkotopiikeilla viittamme tilanteeseen, jossa kirjoittaja
käyttää hyväkseen johonkin edellä esiteltyyn topiikkiin kiinteästi
liittyvää assosiaatioiden joukkoa viitatakseen entiteettiin, jota
itseään ei vielä ole mainittu.

Ajatus lohkotopiikista kytkeytyy Wallace Chafen semiaktiivisuuden
käsitteeseen (1987: 29), ja käytettävissä olemiseen Knud Lambrechtilla
(1996: 99). Esimerkki Dikiltä (mts. 275) on lause *John gave a party
last week, but the music was awful*, jossa *musiikki* on juhlien
käsitteen avulla tekstiin tuotu lohkotopiikki. Lohkotopiikkien
muodostumisessa keskeisiä ovatkin sanojen väliset merkityssuhteet kuten
hyponymia ja meronymia (vrt. Shore 2008: 33). Shoren esityksessä suomen
tekstuaalisesta jäsennyksestä assosiaatioihin perustuviin tekstinosien
välisiin suhteisiin suhtaudutaan varauksella; ilmiötä kuvataan
implisiittisen teeman käsitteellä (Shore 2008, ?).

Huolimatta siitä, että tekstuaalisia suhteita, joita on haasteellista
ankkuroida eksplisiittiisiin tekstinosiin, on kuvattu eri
viitekehyksissä eri tavoin ja suomen kontekstissa ehkä myös vältetty
kuvaamasta, niiden merkitys kirjoittajalle on keskeinen.
Aineistopohjaisissa tutkimuksissa on nimittäin paikallistettu huomattava
joukko hierarkkisesti rakentuvien tekstien rinnalla esiintyviä ns.
moniytimisiä tekstejä, joiden osat ovat ennemmin rinnasteisia, keskenään
tasavertaisia, eikä yhtä voida asettaa toisten ytimeksi (Hiippala
2013)(Komppa 2012)(Vuorijärvi 2013). Vuorijärvi esittelee Paltridgeä
\[täydennä lähdeluetteloon\] mukaillen topiikkipohjaisen rakenteen,
jossa tekstin aihetta avataan ikään kuin osa kerrallaan (Vuorijärvi
2013). Tämä topiikkipohjainen skeema kuvaa hyvin aineistonamme olevien
matkaraporttien tekstilajia, ja topiikin käsittemme rinnastuu monessa
suhteessa mainittujen lähteiden käsitteistykseen. Toisin sanoen puhumme
sisältötopiikista eli aiheesta tai aihepiiristä, josta tekstissä
sanotaan jotakin.

Tutkimusaineisto ja -metodi
===========================

Nyt käsillä olevan tutkimuksen aineisto koostuu siis
yliopisto-opiskelijoiden vaihtokokemuksestaan kirjoittamista teksteistä.
Tarkka tehtävänanto tekstien laatimiseen oli annettu erillisissä
ohjeissa, joissa opiskelijoita pyydetään kirjoittamaan "matkakertomus,
jossa kuvaillaan ja arvioidaan opiskelua ulkomaisessa yliopistossa tai
harjoittelua ulkomailla". Ohjeet sisältävät kahdeksankohtaisen listan
mahdollisesti käsiteltävistä asioista (mm. *etukäteisjärjestelyt*,
*asuminen* ja *merkityksellisyys*). Listaa kehotetaan tulkitsemaan
toteamalla, että "seuraavat ohjeet eivät ole sitovia, mutta ne on hyvä
lukea läpi ennen kirjoittamista". Vaikka ohjeet eivät siis velvoita
noudattamaan juuri tiettyä sisältörakennetta, ylivoimaisesti suurin osa
teksteistä on rakennettu juuri ohjetekstin ehdottaman aiherajauksen
perusteella. Tekstien rakenne on siis kuvion 1 kaltainen: niiden
diskurssitopiikkina on vaihtokokemus ylipäätään, ja tätä ylemmän tason
topiikkia käsitellään jakamalla se alatopiikkeihin, joista tavallisimmat
on lueteltu kuviossa.

![Kuvio 1: Matkakertomustekstien diskurssitopiikki ja
alatopiikit](output/figure/chart.png)

Tässä käsiteltävä lopullinen tutkimusaineisto kattaa kaikkiaan 492
opiskelijoiden laatimaa tekstiä, jotka tutkimuksen ensimmäisessä
vaiheessa annotoitiin kappaleittain[1] siten, että jokaiselle
kappaleelle merkittiin topiikki. Yhteensä kaksikymmentä tekstiä
käsittäneen kokeiluaineiston perusteella päätettiin keskittyä
*asumisesta* kertoviin kappaleisiin siitä syystä, että asumisesta
kirjoitettiin lähes jokaisessa analysoidussa näytetekstissä ja koska
asuminen aiheena havaittiin tavallisesti melko selvärajaiseksi. Koska
tekstit analysoi kaksi eri henkilöä (artikkelin tekijät), näyteaineiston
avulla testattiin myös, kuinka samanlaisia tulkinnat kappaleiden
aiheista olivat. Asumiskappaleiden osalta arvioijien tulkinnat olivat
samoja 45 tapauksessa 47:stä.

Kokeiluaineiston jälkeen koko tutkimusaineisto käytiin läpi siten, että
teksteistä etsittiin vain kappaleita, joiden topiikki oli tulkittavissa
asumiseksi. Kun tämä kaikki tekstit kattava varsinainen
annotointiprosessi saatiin päätökseen, lopulliseksi aineistoksi
muodostui 415 vähintään yhden asumisesta kertovan kappaleen sisältävää
tekstiä. Tekstit ovat keskimäärin 945 sanaa pitkiä ja sisältävät kaiken
kaikkiaan keskimäärin 13 kappaletta. Prosessin tuloksena saatu
tutkimusaineisto on siis kohtalaisen kokoinen, ja sitä voidaan
mahdollisesti jatkossa käyttää erilaisten kvantitatiivisten päätelmien
pohjana. Nyt käsillä olevaa tutkimusta varten päädyttiin kuitenkin
hyödyntämään aineistoa ennen muuta kvalitatiivisesti. Tätä varten
aineistosta eroteltiin tarkempaa analyysia silmällä pitäen
käsiteltäväksi painotettu satunnaisotanta.

Satunnaisotannan painottamisella pyrittiin varmistamaan, että
analysoitava otos edustaa mahdollisimman kattavasti koko
tutkimusaineistoa (satunnaisotantaan liittyvistä periaatteista ks. esim.
Levshina 2015: 8). Otoksen edustavuuden takaamiseksi kaikki 415 tekstiä
kattava korpus rajattiin ja annotoitiin ensin automaattisesti niin
pitkälle kuin mahdollista. Prosessi piti sisällään seuraavat vaiheet:

1.  Määriteltiin, että analysoitavien kappaleiden topiikin asettavat
    virkkeet luokitellaan sen perusteella, mikä sana toimii
    *topiikki-indikaattorina* eli ensimmäisenä leksikaalisena vihjeenä
    kappaleen topiikista. Analysoitavien kappaleiden määrää rajattiin
    siten, että mukaan otettiin ainoastaan sellaiset tapaukset, joissa
    topiikki-indikaattorina oli joskin *asua*-verbin johdos (kuten
    *asunto*, *asuntoasia* tai *asuminen*) tai *asua*-verbi itse.
2.  Huomio kohdistettiin vain niihin 338 tapaukseen, joissa
    *asua*-johdos sijaitsee ensimmäisen asumisesta kertovan kappaleen
    ensimmäisessä virkkeessä. Tällä varmistettiin se, että tarkastelun
    kohteeksi tulee mahdollisimman paljon juuri niitä virkkeitä, joissa
    kirjoittaja todella siirtyy vanhasta topiikista uuteen.
3.  Mukaan valikoituneille kappaleille suoritettiin automaattinen
    syntaktinen ja morfologinen jäsennys sekä lemmatisointi
    hyödyntämällä Turun yliopistossa kehitettyä dependenssijäsennintä
    (Haverinen ym. 2014) ja siihen liittyviä komponentteja.

Jos tutkitaan tarkemmin niitä kategorioita, jotka syntaktinen jäsennin
on merkinnyt tutkimukseen valikoituneiden kappaleiden ensimmäisille
*asua*-johdoksille, saadaan taulukon 1 mukainen jakauma.

<table>
<colgroup>
<col width="12%" />
<col width="13%" />
<col width="34%" />
<col width="34%" />
<col width="5%" />
</colgroup>
<thead>
<tr class="header">
<th align="left"> </th>
<th align="left">Frekvenssi</th>
<th align="left">Selitys</th>
<th align="left">Esimerkki</th>
<th align="left">N</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">dobj</td>
<td align="left">94</td>
<td align="left">objekti</td>
<td align="left"><em>Hankin asunnon</em></td>
<td align="left">47</td>
</tr>
<tr class="even">
<td align="left">root</td>
<td align="left">60</td>
<td align="left">predikaattiverbi</td>
<td align="left"><em>Asuin kerrostalossa</em></td>
<td align="left">30</td>
</tr>
<tr class="odd">
<td align="left">nmod</td>
<td align="left">50</td>
<td align="left">luokittelematon adverbiaali</td>
<td align="left"><em>Asunnon suhteen</em></td>
<td align="left">25</td>
</tr>
<tr class="even">
<td align="left">nmod:gobj</td>
<td align="left">34</td>
<td align="left">nominaalisen verbimuodon objekti</td>
<td align="left"><em>Asunnon hankkiminen</em></td>
<td align="left">17</td>
</tr>
<tr class="odd">
<td align="left">nsubj</td>
<td align="left">32</td>
<td align="left">subjekti</td>
<td align="left"><em>Asuminen järjestyi</em></td>
<td align="left">16</td>
</tr>
<tr class="even">
<td align="left">nmod:poss</td>
<td align="left">29</td>
<td align="left">omistusrakenteen kohde</td>
<td align="left"><em>Asuntoloiden vuokrataso</em></td>
<td align="left">14</td>
</tr>
<tr class="odd">
<td align="left">nsubj:cop</td>
<td align="left">21</td>
<td align="left">kopulalauseen subjekti</td>
<td align="left"><em>Asuntola on uusi</em></td>
<td align="left">10</td>
</tr>
<tr class="even">
<td align="left">muu</td>
<td align="left">18</td>
<td align="left">esim. infinitiivitäydennykset</td>
<td align="left"><em>Halusin asumaan paikallisten kanssa</em></td>
<td align="left">9</td>
</tr>
<tr class="odd">
<td align="left">Yht.</td>
<td align="left">338</td>
<td align="left">---</td>
<td align="left">---</td>
<td align="left">168</td>
</tr>
</tbody>
</table>

Taulukko 1: Asua-johdosten jakautuminen eri syntaktisiin kategorioihin.

Taulukon Frekvenssi-sarakkeesta nähdään paitsi se, että yhteensä edellä
kuvattujen kolmen annotointi- ja rajausvaiheen jälkeen jäljelle jäi 338
tekstiä, myös se, että selvästi tavallisimpia topiikki-indikaattoreita
olivat objektina esiintyvät asua-johdokset. Kategoriat, joiden edustajia
oli yhteensä alle kymmenen, niputettiin yhdeksi *muu*-kategoriaksi.
Varsinainen satunnaisotanta tehtiin taulukossa esitettyjen kategorioiden
perusteella siten, että jokaisesta taulukossa luetellusta ryhmästä
(mukaan lukien *muu*-ryhmä) valittiin satunnaisesti ryhmän
kokonaisfrekvenssin puolikasta vastaava määrä tapauksia (ks. taulukon
viimeinen sarake).[2] Nämä 168 tapauksesta otettiin varsinaisen
laadullisen analyysin kohteeksi.

Laadullisen analyysin tavoitteena oli ryhmitellä aineistosta erotellut
168 tekstiä siten, että yhteen ryhmään päätyisivät aina ne tavat asettaa
topiikki, jotka syntaktisilta tai funktionaalisilta ominaisuuksiltaan
muistuttavat toisiaan. Jokaista topiikkia asettavaa virkettä tutkittiin
erikseen laajemmassa tekstiyhteydessään, minkä jälkeen sitä verrattiin
muihin virkkeisiin ja määriteltiin, oliko kyseessä jokin uusi, muista
erottuva tapausjoukko vai ennemminkin jokin jo muodostettuun joukkoon
kuuluva tapaus. Tapauksia ei siis ryhmitelty minkään ennalta
määriteltyjen kriteerien pohjalta, vaan sillä perusteella, mitkä
tapaukset muistuttivat toisiaan.

Metodimme muistuttaa jonkin verran Vuorijärven (2013: 116) mainitsemaa
korpuslingvistisessä tekstianalyysissä käytettyä menetelmää (ks. Biber
ym. 2007), jossa analyysiin otettavat tekstit käydään ensin yksitellen
läpi, minkä jälkeen kukin teksti pyritään pilkkomaan tiettyä
viestitätarkoitusta toteuttaviin, erikseen nimettäviin jaksoihin. On
kuitenkin olennaista huomata se lähtökohtaero, ettei nyt käsillä
olevassa tutkimuksessa niinkään etsitä eri tekstijaksojen
viestintätarkoituksia, vaan liikutaan puhtaasti topiikkien tasolla
kysymällä, miten jokin uusi aihe esitellään lukijalle. Toinen ero on
siinä, että tarkasteltavien tekstijaksojen rajauksessa lähtökohtana
pidetään kirjoittajan itsensä tekemää ortografista kappalejakoa --
kirjoittajan omaa näkemystä siitä, milloin tekstissä siirrytään
sellaiseen uuteen jaksoon, joka ansaitsee tulla erotetuksi edeltävästä
tekstistä. Kolmanneksi tämän tutkimuksen metodin erottaa edellä
mainituista se, ettei analyysin tuloksena syntyneitä ryhmiä pyritä
nimeämään (vrt. Vuorijärvi 2013: 117), vaan ne määritellään ainoastaan
suhteessa toisiin teksteihin.

....vielä kappale ryhmittelyn perusteista ja siitä, ettei semant.
kriteerejä käytetty...

Tulokset
========

Edellä kuvatun laadullisen analyysin tuloksena tutkimusaineiston tekstit
jaoteteltiin 13 ryhmään, joita osiossa 4.1. luonnehditaan yhden
edustavan esimerkin avulla. Kuten metodin kuvauksen yhteydessä
todettiin, tässä kuvatut eri topiikin asettamistapoja edustavat ryhmät
on muodostettu systemaattisesti sijoittamalla toisaan muistuttavat
tapaukset samaan kategoriaan. Ryhmien väliset rajat eivät
luonnollisestikaan ole suoraviivaisia, ja jaottelun olisi voinut tehdä
muillakin tavoilla. Eri ryhmät ovat lisäksi enemmän tai vähemmän
läheisessä yhteydessä toisiinsa, ja näitä linkkejä on tässä esitetyssä
kuvauksessa pyritty osoittamaan. Vaikka varsinainen ryhmäjako perustuu
laadulliseen samankaltaisuuteen, tulkitaan osiossa 4.2. analyysin
tulosta eli itse jaottelua tilastollisin menetelmin.

Laadullinen analyysi
--------------------

Taulukkoon 2 olemme koonneet edustavat esimerkit kustakin ryhmästä.
Niiden rinnalla on hyvin tiivis kuvaus topiikin asettamisen tavoista ja
lisäksi muutama sana juuri kyseisen esimerkkivirkkeen kontekstista.
Rajallisesta sivumäärästä johtuen syvennymme seuraavassa tarkemmin vain
niihin ryhmiin, jotka osoittautuivat kirjoittamisen näkökulmasta
erityisen kiinnostaviksi. Ryhmät on taulukossa esitetty koon mukaisessa
järjestyksestä suurimmasta pienimpään. Viittaamme ryhmiä edustaviin
virkkeisiin jatkossa samoin, kuin viittaisimme numeroituihin
esimerkkeihin.

<table>
<colgroup>
<col width="7%" />
<col width="30%" />
<col width="30%" />
<col width="30%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Ryhmä</th>
<th align="left">Topiikkia asettava virke</th>
<th align="left">Konteksti</th>
<th align="left">Siirtymän toteutus</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">1</td>
<td align="left"><em>Asuntoni sain vuokrattua Apartiksen( paikallinen TOAS) kautta.</em></td>
<td align="left">Käsittelee ennakkovalmisteluja yms. Lopuksi reflektoi osaamistaan kielikurssilla.</td>
<td align="left">Alatopiikilla, vaikka ylätopiikkia ei ilmipantu.</td>
</tr>
<tr class="even">
<td align="left">2</td>
<td align="left"><em>Vaihtoni aikana asuin Grandmontin asuntolassa.</em></td>
<td align="left">Kertoo, missä asui vaihtonsa aikana; kuvailee sisustuksen, kämppäkaverit ja vuokran.</td>
<td align="left">Esittelytopiikilla. Predikaattina on asua-verbi. Kertoo, missä kirjoittaja on asunut.</td>
</tr>
<tr class="odd">
<td align="left">3</td>
<td align="left"><em>Olin löytänyt asunnon ensimmäiseksi kuukaudeksi Airbnb:n kautta ennen Italiaan saapumista.</em></td>
<td align="left">Kertoo, mitä tapahtunut ennen kuvattavaa jaksoa. Kuvailee tarkemmin sijaintia, kulkuyhteyksiä yms.</td>
<td align="left">Esittelytopiikilla, mutta aikarakenteltaan monitasoisempi kuin ryhmä 3.</td>
</tr>
<tr class="even">
<td align="left">4</td>
<td align="left"><em>Asuminen, tai siis lähinnä asunnon hankkiminen, oli varmaankin vaihdon hankalin juttu.</em></td>
<td align="left">Arvioi edeltävässä kurssitarjonnan tasoa, paperiasioiden hoitumista yms.</td>
<td align="left">Diskurssista johdetulla alatopiikilla, jota indikoi usein deverbaalisubstantiivi. Luonnehtii kirjoittajan subjektiivista kokemusta.</td>
</tr>
<tr class="odd">
<td align="left">5</td>
<td align="left"><em>Asuntoloista valitsin Julius Raab Heimin vanhojen matkakertomusten perusteella.</em></td>
<td align="left">Kuvannut vaihtoon hakua ja kotimaan järjestelyjä. Maininnut jo paikallisista asuntolavaihtoehdoista.</td>
<td align="left">Edeltävässä kappaleessa annetun tai hiukan kauempaa palautetun topiikin avulla. Kuuluvat toissijaisesti johonkin toiseen alaryhmään.</td>
</tr>
<tr class="even">
<td align="left">6</td>
<td align="left"><em>Ulkomaisille opiskelijoille tarkoitettu asuntola on vain kolme vuotta vanha ja täten melko moderni.</em></td>
<td align="left">Edellinen kappale lennosta ja saapumisesta.</td>
<td align="left">Muistuttavat 2. ryhmän tapauksia, kytkös implisiittisempi, usein väliotsikko. Luonnehtii asuntoa / asuntolaa konkreettisesti.</td>
</tr>
<tr class="odd">
<td align="left">7</td>
<td align="left"><em>Itselläni kävi tuuri asunnon suhteen löytäessäni edullisen huoneen Chelseasta aivan Manhattanin keskeltä.</em></td>
<td align="left">Tekstin viimeinen kappale. Edellä arvioinut kokemustaan kokonaisuutena.</td>
<td align="left">Alatopiikin avulla. Muistuttaa 1. ryhmää, mutta sisältönä verrataan omia kokemuksia toisten kokemuksiin.</td>
</tr>
<tr class="even">
<td align="left">8</td>
<td align="left"><em>Asuminen Tokiossa on aika kallista.</em></td>
<td align="left">Kappale melkein tekstin lopussa. Edellä kuvannut vapaa-ajan mahdollisuuksia.</td>
<td align="left">4. ryhmän tapaan, mutta jakaen maailmantietoa, ei eksplikoiden omia kokemuksia.</td>
</tr>
<tr class="odd">
<td align="left">9</td>
<td align="left"><em>Suurlähetystön henkilökunta tarjosi resurssiensa puitteissa apuaan mm. maahantuloon, käytännön järjestelyihin sekä asunnon löytämiseen liittyvissä asioissa.</em></td>
<td align="left">Edellä kuvannut hakuprosessia. Jatkaa vuokratasoon ja hintoihin.</td>
<td align="left">Esittelytopiikin avulla, mutta kirjoittaja ei ole agentiivinen toimija. Fokuksessa joku muu keskeinen toimija.</td>
</tr>
<tr class="even">
<td align="left">10</td>
<td align="left"><em>Lensin Wieniin sunnuntaina ja lento-kentältä suuntasin suoraan asunnolleni.</em></td>
<td align="left">Tekstin alkupuolella -- edellä vain hakuprosessin kuvaus.</td>
<td align="left">edellisiä implisiitisempi, kuitenkin uuden topiikin avulla. Kertova tekstityyppi ja aikamuoto yleensä imperfekti. Narraatio.</td>
</tr>
<tr class="odd">
<td align="left">11</td>
<td align="left"><em>Sitten pari sanaa asumisesta.</em></td>
<td align="left">Edellä yksityiskohtaisesti esim. seminaarien opintopisteistä.</td>
<td align="left">metatekstin kautta. Uusi topiikki, joka tuodaan tekstiin eksplisiittisesti.</td>
</tr>
<tr class="even">
<td align="left">12</td>
<td align="left"><em>Saapuessani Varsovaan minulla oli onneksi jo asunto tiedossa.</em></td>
<td align="left">Edellä kieltenopiskelusta, jatkaa hintoihin.</td>
<td align="left">uuden topiikin avulla, joka avausvirkkeen loppupuolella. Ajallinen jännite, katsotaan kuvatusta aikapisteestä taaksepäin.</td>
</tr>
<tr class="odd">
<td align="left">13</td>
<td align="left"><em>Lähes kaikki Bratislavan kauppakorkeakoulun vaihto-opiskelijat asuivat Ekonom-nimisessä dormitoryssa.</em></td>
<td align="left">Kuvannut saapumista ja tutor-toimintaa.</td>
<td align="left">7. ryhmän tapaan, mutta samaistuen, ei kontrastoiden muiden vaihto-opiskelijoiden toimintaan. Alaotsikko tyypillinen.</td>
</tr>
</tbody>
</table>

Taulukko 2: Esimerkit laadullisen analyysin tuloksena syntyneistä
ryhmistä

Aineiston isoimman ryhmän muodostavat esimerkin 1 kaltaiset topiikkia
asettavat virkkeet. Topiikki-indikaattorina on tässä *asuntoni*-sana. Se
on tekstin ensimmäinen eksplisiittinen maininta topiikista; asumiseen
tai asuntoon ei ole viitattu edeltävissä kappaleissa. *asuntoni* on
tulkittu analyysissämme alatopiikiksi (ks. osio x.x edellä), vaikka
esimerkissä 1 ei täytykään Dikin (1989: 275) kuvailema ehto siitä, että
varsinainen ylätopiikki olisi erikseen esitelty lukijalle (vrt. myös
Guijarro 2001: 110). Asunto tai asuminen on tuotu tekstiin ilman
ennakkomainintoja tai esittelyjä, se aivan kuin oletetaan lukijan
käytettävissä olevaksi entiteetiksi (vrt. Chafe 1987: 29; Lambrecht
1996: 99). Voisi jopa sanoa, että esimerkin 1 kaltaiset tapaukset eivät
niinkään aseta topiikkia vaan ennemmin käyttävät jo asetetetuksi
oletettua topiikkia (vrt. implisiittinen teema Shore (2008)). Tekstin
koherenssi rakentuu tässä, kuten useimmissa muissakin ryhmän 1[3]
tapauksissa, lähinnä tehtävänannon tarjoaman kysymyspatteriston ja
saatavilla olevien mallitekstien varaan. Tekstejä voisi kuvata
listamaisiksi.

Seuraavan kiinnostavan ryhmän muodostavat esimerkin 2 kaltaiset
tapaukset, joissa topiikki-indikaattorina on persoonamuotoinen
*asua*-verbi. Virkkeiden pääasiallinen sisältö on yleensä informaatio
siitä, missä kirjoittaja on vaihtonsa aikana asunut. Tapaukset ovat
edellistä ryhmää selkeämmin johdantoja uuteen aiheeseen, ja Dikin
jaottelun mukaisesti esimerkin 2 lopussa mainittu *asuntola* muodostaa
(osiossa x.x. määritellyssä termin teknisessä merkityksessä) uuden
topiikin (1989: 269). Vastaavat *asuin paikassa X* -tyyppiset rakenteet
ovat siis keinoja esitellä *paikka X*, josta tällaisella virkkeellä
alkava kappale kertoo.

Kertova tekstityyppi on aineistona olevissa matkakertomuksissa
tyypillinen, mikä näkyy useammassakin ryhmässä. Ryhmässä 10 asumisesta
raportoidaan kertovan tekstityypin avulla. Aikamuoto ryhmässä 10 on
tyypillisesti imperfekti. Esimerkin 3 edustamat tapaukset ovat
ajallisesti muita monitasoisempia. Lukija johdatetaan kappaleen
topiikkiin kuvaamalla jotakin, mikä on tapahtunut ennen sitä ajanjaksoa,
jolle varsinainen käsiteltävä topiikki sijoittuu.

Oman selvän kokonaisuutensa muodostavat myös erilaiset tavat aloittaa
kappale luonnehtimalla omia kokemuksia. Esimerkissä 4 topiikkia indikoi
*asuminen*, mikä tässä ryhmässä onkin varsin tyypillistä: jostakin
varsinaisen diskurssitopiikin osa-alueelta tiivistetään oma kokemus
esim. deverbaalijohdoksella tai sen ympärille muodostuneella
lausekkeella, jota sitten luonnehditaan predikatiivilauseella. Näissä
tapauksissa kuvataan, että *asunnon hakeminen oli helppoa* tai miten
*kaikkein vaikeinta oli asunnon löytäminen*. Strategiana on omia
onnistumisia ja epäonnistumisia arvioiden kertoa, miten asiat ovat
sujuneet. Informaatiorakenteen kannalta nämä tapaukset ovat monesti
ryhmän 1 tapaan alatopiikkeja. Esimerkki4 on kuitenkin esimerkkiä 1
selvemmin topiikkia asettava virke, sillä siinä asumisen rooli yhtenä
vaihtokokemuksen osana on ilmaistu eksplisiittisesti. Osittain
samankaltaista reflektointia ja omien näkemysten jakamista edustaa
esimerkki 7 (n=10). Ryhmän ominaispiirteenä on vertailu tai
kontrastointi muihin vaihdossa olleisiin opiskelijoihin. Edellä esitetyn
ryhmän tavoin kirjoittajat käyttävät alatopiikkeja, ja olettavat
indikaattorisanan implikoiman topiikin jossain määrin esimerkin 1
kaltaisesti jo asetetuksi. Yhdessäkään ryhmän 7 tapauksessa ei ole
asumiseen viittaavaa väliotsikkoa.

Siinä missä esimerkki 4 on informaatiorakenteen kannalta omasta
vaihtokokemuksesta lohkaistu alatopiikki, ankkuroituu esimerkki 8 siihen
fyysiseen paikkaan, jossa vaihto tapahtui. Ryhmän 8 (n=10) kirjoittajat
eivät lähdekään liikkeelle omista kokemuksistaan, vaan käsittelevät
tilannetta laajemmin, jakaen maailmantietoa lukijalleen. Kahdessa
(mukaan lukien esimerkki 8) asumisesta kertovaa kappaletta edeltää
väliotsikko Asuminen. Yleistys kirjoittajan oman kokemuspiirin
ulkopuolelle voidaan kuitenkin tehdä myös toisella tavalla. Esimerkissä
9 ja kahdeksassa muussa tapauksessa tämä tapahtuu keskittymällä johonkin
ulkoiseen agenttiin (tämä sanavalinta vaivaa minua, mutten keksi mitään
parempaakaan), jonka toimet vaikuttavat kirjoittajaan yleisesti ja
asumisen järjestymiseen erityisesti. Esimerkissä 9 on
informaatiorakenteen kannalta katsottuna kyse esimerkkien 2, 3 ja 6
tapaan uudesta topiikista, mutta sen esittely toteutetaan hyödyntämällä
jotakin tekstin kannalta keskeistä toimijaa, tässä tapauksessa
suurlähetystön henkilökuntaa. Kuten ryhmän 7 kohdalla, myös ryhmässä 9
yli puolessa tapauksia (55.56 %) asumisesta kertovaa kappaletta edeltää
väliotsikko.

Esimerkissä 5 indikaattorina on *asuntoloista*-sana. Ilman kontekstia
tarkasteltuna tämäkin tapaus vaikuttaa samalta kuin listamainen
esimerkki, mutta laajemman analyysin tuloksena selvisi, että kirjoittaja
on jo aiempana, kirjoittaessaan etukäteisjärjestelyistä ja kohdemaahan
saapumisesta, rakentanut kuvaa paikallisista asuntolavaihtoehdoista ja
asuntolassa elämisestä. Tämän ryhmän tekstit sijoittuvatkin
toissijaisesti myös johonkin toiseen alaryhmään, mutta ovat erottuneet
omasta alaryhmästään kontekstin tarkastelun vaiheessa. Esimerkin 5
kaltaisia aiempaan kontekstiin tietoisesti sidottuja tapauksia on
aineistossa 14 kappaletta. Näissä tapauksissa kyse on virketasolla
tarkasteltuna joko annetuista topiikeista -- jos kontekstuaalinen linkki
on muodostettu suhteellisen lähellä tässä käsiteltävää varsinaista
asumiskappaletta -- tai, jos edellinen maininta on selvästi kauempana,
palautetuista topiikeista (Dik 1989: 270--271). X:ssä tämän ryhmän
virkkeessä kappaletta edeltää välitotsikko.

Tilastollinen tarkastelu
------------------------

Edellä (taulukko 2 ) esitimme tavan ryhmitellä asumisesta kertovat
tekstikappaleet sen mukaan, miten kirjoittaja toteuttaa siirtymän uuteen
aiheeseen. Seuraavassa sovellamme laadullisen analyysin tuloksena
saatuun ryhmäjakoon tilastollisia menetelmiä, tarkemmin ottaen
ehdollisia päätöksentekopuita (conditional inference trees).

Ehdolliset päätöksentekopuut ovat regressiotyyppinen
luokittelumenetelmä, jossa yhden tai useamman selittävän muuttujan
assosiaatiota selitettävään muuttujaan (termeistä ks. Ketokivi 2015:
131) tarkastellaan sarjana tutkimusaineistoa jaottelevia päätöksiä
(Levshina 2015: 291). Meidän tutkimukseemme sovellettuna tämä tarkoittaa
sen selvittämistä, mitkä aineiston 168 tapauksen ominaisuudet
(selittävät muuttujat) parhaiten ennustavat sen, mihin kolmestatoista
ryhmästä (selitettävä muuttuja) tapaus on luokiteltu. Käytössämme ovat
taulukon 3 mukaiset selittävät muuttujat.

<table style="width:93%;">
<colgroup>
<col width="41%" />
<col width="51%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Muuttujan nimi ja lyhenne</th>
<th align="left">Muuttujan arvot</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Koneellisen jäsentimen topiikki-indikaattorille asettama syntaktinen rooli (dep)</td>
<td align="left">Arvot esitetty taulukossa 1, kuitenkin lavennettuna siten, että arvot <em>nsubj</em> ja <em>nsubj:cop</em> yhdistettiin yhdeksi subjektin kategoriaksi (<em>subj</em>) ja arvot <em>nmod:poss</em> sekä <em>nmod:gobj</em> yhdeksi <em>nmod:x</em>-kategoriaksi, jolla viitattiin kaikkiin kompleksisiin nominaalirakenteisiin (<em>asunnon hankinta</em>, <em>asumisen järjestäminen</em>).</td>
</tr>
<tr class="even">
<td align="left">Topiikki-indikaattorin sijainti virkkeessä (sij)</td>
<td align="left">Kaksi arvoa a) Tapaukset, joissa topiikki-indikaattori on koko virkkeen ensimmäisenä. b) Muut tapaukset.</td>
</tr>
<tr class="odd">
<td align="left">lauseen predikaattiverbin persoona (pers)</td>
<td align="left">Kaksi arvoa: a) Tapaukset, joissa predikaattiverbi on ensimmäisessä persoonassa ja b) Muut tapaukset.</td>
</tr>
<tr class="even">
<td align="left">Side muuhun tekstiin (side)</td>
<td align="left">Neljä arvoa: a) Tapaukset, joissa topiikki asetetaan viittaamalla selkeästi johonkin edellä muodostettuun linkkiin (<em>linkki</em>) b) Tapaukset, joissa asumistopiikkia on pohjustettu edellisessä kappaleessa, muttei niin selvästi, että kyseessä olisi linkkitapaus (<em>edel.</em>) c) Tapaukset, joissa asumiskappaletta edeltää väliotsikko (<em>ots</em>) d) Tapaukset, joissa mitään edellä kuvatuista siteistä ei ole (<em>x</em>).</td>
</tr>
<tr class="odd">
<td align="left">Topiikki-indikaattorin morfologinen rakenne (morf)</td>
<td align="left">Kolme arvoa: a) finiittiverbit b) infintiivimuodot (mukaan lukien minen-johdokset) c) substantiivit.</td>
</tr>
<tr class="even">
<td align="left">Aikamuoto (tense)</td>
<td align="left">Neljä arvoa: a) preesens, imperfekti, pluskvamperfekti/perferkti<a href="#fn1" class="footnoteRef" id="fnref1"><sup>1</sup></a>, ellipsi (--).</td>
</tr>
</tbody>
</table>
<div class="footnotes">
<hr />
<ol>
<li id="fn1"><p>Perfektitapauksia aineistossa oli vain yksi ja sekin konditionaalissa, joten molemmat suomen liittoaikamuodot yhdistettiin samaan kategoriaan.<a href="#fnref1">↩</a></p></li>
</ol>
</div>

Taulukko 3: Tilastollisen analyysin selittävät muuttujat

Tässä käytetty päätöksentekopuu rakennettiin R-ohjelmiston
*party*-kirjastoon kuuluvaa *ctree*-funktiota (Hothorn ym. 2006)
käyttäen.[5] Analyysin tulos on esitetty kuviossa 3.

<img src="/home/juho/projects/100-tapaa-indikoida-topiikkia/output/koko_artikkeli_files/figure-markdown_strict/unnamed-chunk-4-1.png" alt="Kuvio 3: Topiikkia asettavien ryhmien rakenne luokittelupuun avulla tarkasteltuna" angle=90 />
<p class="caption">
Kuvio 3: Topiikkia asettavien ryhmien rakenne luokittelupuun avulla
tarkasteltuna
</p>

Kuviossa 3 tutkimusaineisto on jaettu kymmeneen ryhmään (kuvion
alimmalla rivillä esitetyt pylväskaaviot) edellä kuvattujen selittävien
muuttujien perusteella. Kuvio esittää selittävien muuttujien vaikutuksen
sarjana päätöksiä (kuvion ympyränmuotoiset noodit), jotka on numeroitu
yhdestä 19:ään, esimerkiksi: *jos jonkin tapauksen dependenssirooli on
predikaatti (noodi 1) ja pääverbin persoona ensimmäinen (noodi 15) ja
jos lisäksi tapausta ei edellä väliotsikko, kyseessä on aina ryhmään 2
kuuluva tapaus (noodi 18)*. Jos taas dependenssirooli on predikaatti
(noodi 1), joka ei kuitenkaan esiinny ensimmäisessä persoonassa, on
kyseessä useimmiten ryhmän 13 tapaus, vaikka muutkin vaihtoehdot ovat
mahdollisia. Jokaisen kuvion haarauman kohdalle on myös merkitty p-arvo,
joiden avulla voidaan arvioida kunkin haarauman merkitsevyyttä (Levshina
2015: 292). Korkein p-arvo kuviossa 3 on noodilla 15, joka sekin on vain
noin yhden prosentin luokkaa, mikä tarkoittaa että kuviossa esitetyt
jaot ovat kaiken kaikkiaan merkitseviä (Baayen 2012: 69; p-arvoista ks.
esim. Levshina 2015: 10).

Oleellista tässä esitetyssä päätöksentekopuussa on, että vaikka itse
luokittelu ryhmiin tehtiin puhtaasti artikkelin kirjoittajien tulkinnan
perusteella ja kustakin ryhmästä annettiin edellä funktionaalinen
kuvaus, on ryhmiä mahdollista kuvailla melko pitkälle myös
rakenteellisten ominaisuuksien valossa. Karkeasti ottaen voidaan todeta,
että suurin osa laadullisen analyysin tuloksena laadituista
kolmestatoista ryhmästä pystytään päättelemään hyödyntämällä kolmea[6]
yksinkertaista rakenteellisen mikrotason muuttujaa: verbin persoonaa,
aikamuotoa ja indikaattorisanan dependenssiroolia. Taulukossa 4 on
tiivistetty näiden muuttujien vaikutus topiikkia asettavan virkkeen
päätymiseen johonkin laadullisessa analyysissa määritellyistä ryhmistä.

<table>
<colgroup>
<col width="16%" />
<col width="17%" />
<col width="30%" />
<col width="8%" />
<col width="26%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Verbin persoona</th>
<th align="left">Verbin aikamuoto</th>
<th align="left">Indikaattorisanan dependenssirooli</th>
<th align="left">ryhmä</th>
<th align="left">luokittelupuun loppunoodit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"><em>1.</em></td>
<td align="left"><em>imperfekti</em></td>
<td align="left"><em>ei predikaatti</em></td>
<td align="left">1</td>
<td align="left">7</td>
</tr>
<tr class="even">
<td align="left"><em>1.</em></td>
<td align="left">--</td>
<td align="left"><em>predikaatti</em></td>
<td align="left">2</td>
<td align="left">17 ja 18</td>
</tr>
<tr class="odd">
<td align="left">--</td>
<td align="left"><em>pl.perf/perf.</em></td>
<td align="left">--</td>
<td align="left">3</td>
<td align="left">12</td>
</tr>
<tr class="even">
<td align="left"><em>muu kuin 1.</em></td>
<td align="left"><em>imperfekti</em></td>
<td align="left"><em>osa kompleksista lauseketta</em></td>
<td align="left">4</td>
<td align="left">9</td>
</tr>
<tr class="odd">
<td align="left">--</td>
<td align="left"><em>imperfekti</em></td>
<td align="left"><em>subjekti</em></td>
<td align="left">6</td>
<td align="left">11</td>
</tr>
<tr class="even">
<td align="left">--</td>
<td align="left"><em>preesens</em></td>
<td align="left"><em>ei predikaatti</em></td>
<td align="left">8</td>
<td align="left">13</td>
</tr>
<tr class="odd">
<td align="left"><em>muu kuin 1.</em></td>
<td align="left">--</td>
<td align="left"><em>predikaatti</em></td>
<td align="left">13</td>
<td align="left">19</td>
</tr>
<tr class="even">
<td align="left"><em>muu kuin 1.</em></td>
<td align="left"><em>imperfekti</em></td>
<td align="left"><em>ei predikaatti, ei subjekti, ei osana kompleksista lauseketta</em></td>
<td align="left">7 ja 9</td>
<td align="left">10</td>
</tr>
</tbody>
</table>

Taulukko 4: Kvantitatiivisesti pääteltävissä olevat ryhmät

Taulukon mukaan ryhmä 1 voidaan rakenteiden tasolla määritellä siten,
että siinä on nominaalinen topiikki-indikaattori, jonka pääverbi
esiintyy ensimmäisessä persoonassa ja imperfektissä. Ryhmän 4 puolestaan
erottaa muista se, että asumisaiheeseen viitataan siinä jollakin
kompleksisella lausekkeella, kuten *asunnon hankinta* tai *asumisen
järjestäminen*. Ryhmä 3 taas voidaan määritellä ennen kaikkea aikamuodon
pohjalta: siihen kuuluvat tapaukset, joissa verbi on
pluskvamperfektissä. Ainoastaan ryhmien 10, 11 ja 12 osalta ei tässä
esitetyn päätöksentekopuun perusteella voida esittää selkeitä piirteitä,
jotka johtaisivat tapauksen sijoittamiseen juuri näihin ryhmiin. Lisäksi
on huomattava, että esimerkin sijoittaminen ryhmään 5 on perustunut
täysin artikkelin kirjoittajien tulkintaan: se, että tulevaa topiikkia
on eksplisiittisesti pohjustettu aiemmassa tekstissä, ei ole
pääteltävissä siitä, minkälaisia rakenteita topiikkia asettavassa
virkkeessä on käytetty.

Päätelmäluvun puolelle se, miä tästä kaikesta seuraa.

Päätelmät
=========

Tarkastelimme tässä tutkimuksessa tekstikappaleen topiikin muodostumista
korpusvetoisesti, kahdella menetelmällä. Tavoitteenamme oli selvittää,
millaisia tapoja yliopisto-opiskelijat käyttävät matkaraporteissaan
saman topiikin asettamiseen ja miten näitä tapoja voidaan määritellä
toisaalta funktionaalisesti, toisaalta syntaktisesti.

Tutkimuksen aineistona oli yliopisto-opiskelijoiden kirjoittamista
matkakertomuksista koostettu korpus, ja osa artikkelin löydöksistä
liittyykin eittämättä myös tekstilajille ominaisiin ilmaisutapoihin,
vaikka tutkimuksen keskiössä olivat virkkeet ja niiden väliset suhteet.
Käyttämämme aineisto ja menetelmät eivät tarjoa vastauksia siihen, miksi
kirjoittajat ovat päätyneet ehkä hieman luettelomaisestikin
kirjoittamaan ohjeessa annetuista aiheista sen sijaan, että olisivat
kirjoittaneet hierarkkisesti rakentuneen tekstin.

Laadullisen analyysin tuloksena erotimme 13 erilaista tapaa toteuttaa
kappaleenalkuinen siirtymä topiikista toiseen. Pääpiirteissään näiden 13
ryhmän eroavaisuudet palautuvat 1) siihen, toteuttaako kappale kertovaa,
kuvailevaa vai erittelevää tekstityyppiä (vrt. Juvonen 2014b: 81--82) 2)
siihen, millaisessa suhteessa aloitusvirkkeessä esitetty topiikki on
aiempaan tekstiin ja 3) siihen, millaisesta näkökulmasta käsin
kirjoittaja lähestyy tekstinsä aihetta. Tilastollisessa rakenteiden
tason analyysissa suurin osa laadullisen analyysin tuloksena laadituista
ryhmistä pystyttiin lopulta päättelemään hyödyntämällä kolmea
yksinkertaista muuttujaa: predikaatin persoonaa ja aikamuotoa sekä
indikaattorisanan dependenssiroolia.

Esimerkiksi tekstilajeja tai argumentointia käsitellessään opettajan tai
oppimateriaalin tekijän on usein turvauduttava melko abstrakteihin
komponentteihin ja määritelmiin. Yhtenä tämän tutkimuksen tuloksena
ovatkin funktionaalisten kuvausten lisäksi tuotetut rakenteiden tason
määritelmät, jotka tarjoavat vaihtoehtoisen lähestymistavan kappaleiden
rakentamisen opettamiseen ja omaksumiseen. Tämä lähestymistapa voi olla
erityisen hedelmällinen suomea toisena tai vieraana kielenä
kirjoittaville: konkreettiset kielenaineksiin viittaavat ohjeet kuten
"rakenna lause yksikön kolmannessa persoonassa" tai "muodosta
käsiteltävästä asiasta minen-substantiivi ja kuvaile sitä adjektiivilla"
voivat monissa tilanteissa olla helpommin lähestyttäviä kuin abstraktit
kuvaukset siitä, minkälaisia kappaleiden tulisi olla. Tässä tuotetut
ryhmittelyt voisivatkin toimia lähtölaukauksena myös erilaisia
todellisista teksteistä poimittuja mallirakenteita esittelevälle
fraasipankille (vrt. Chitez ym. 2015). Juuri tällaiset materiaalit
istuvat hyvin ajatukseen uudesta kirjoittajasta, joka ei niinkään kysy,
miten asiat pitäisi tehdä, vaan etsii malleja siitä, millä eri tavoilla
on jo tehty.

Baayen, Rolf H. 2012. *Analyzing Linguistic Data: A Practical
Introduction to Statistics using R*. Cambridge: Cambridge university
press.

Biber, Douglas, Ulla Connor & Thomas A. Upton 2007. *Discourse on the
move: Using corpus analysis to describe discourse structure* Vsk. 28.
John Benjamins Publishing.

Chafe, Wallace 1987. Cognitive constraints on information flow.
Teoksessa: Russell S. Tomlin (ed.) *Coherence and Grounding in Discourse
: Outcome of a Symposium, Eugene, Oregon, June 1984.* John Benjamins
Publishing Company.

Chitez, Madalina, Christian Rapp & Otto Kruse 2015. Corpus-supported
academic writing: how can technology help? Teoksessa: *Critical
CALL-Proceedings of the 2015 EUROCALL Conference, Padova, Italy, F.
Helm, L. Bradley, and S. Thouësny.(Eds)*, 125–132. Dublin, Ireland:
Research-publishing.net.

Dik, Simon C. 1989. *The Theory of Functional Grammar, Part I: The
Structure of the Clause, Vol. 9 of Functional Grammar Series*.
Dordrecht: Foris Publications.

Givón, Talmy 1983. *Topic continuity in discourse*. John Benjamins
Publishing Company.

Guijarro, A. Jesús Moya 2001. Topicality chains in two discourse genres.
*Estudios Ingleses de la Universidad Complutense* 9: 103–128.

Haverinen, Katri, Jenna Nyblom, Timo Viljanen, Veronika Laippala, Samuel
Kohonen, Anna Missilä, Stina Ojala, Tapio Salakoski & Filip Ginter 2014.
Building the essential resources for Finnish: the Turku Dependency
Treebank. *Language Resources and Evaluation* 48:3, 1–39.

Hiippala, Tuomo 2013. Modelling the structure of a multimodal artefact.

Hothorn, Torsten, Kurt Hornik & Achim Zeileis 2006. Unbiased Recursive
Partitioning: A Conditional Inference Framework. *Journal of
Computational and Graphical Statistics* 15:3, 651–674.

Jisa, Harriet & Liliana Tochinsky 2009. Developing a personalized stance
through linguistic means in typologically different languages. Written
expository discourse. *Written Language & Literacy* 12:1, 1–25.

Juvonen, Riitta 2014a. Kirjoitelma ja tekijän ääni: kehystämisen
yhdyslauseet suomenkielisen ylioppilasaineen dialogisuuden hallinnassa.

Juvonen, Riitta 2014b. Näkökulma kirjoitelman dialogisuuteen: Kuinka- ja
miten-yhdyslauseet ylioppilasaineessa. *Virittäjä* 118:1, 72.

Juvonen, Riitta, Mikko Virtanen & Eero Voutilainen 2012. Fennistisen
tekstilajitutkimuksen suuntia. *Vesa Heikkinen, Eero Voutilainen, Petri
Lauerma, Ulla Tiililä & Mikko Lounela (toim.), Genreanalyysi.
Tekstilajitutkimuksen käsikirja* 453–469.

Ketokivi, Mikko 2015. *Tilastollinen päättely ja tieteellinen
argumentointi* 2. laaj. laitos. Helsinki: Gaudeamus.

Komppa, Johanna 2012. Retorisen rakenteen teoria suomi toisena
kielenä-ylioppilaskokeen kirjoitelman kokonaisrakenteen ja kappalejaon
tarkastelussa.

Lambrecht, Knud 1996. *Information structure and sentence form: Topic,
focus, and the mental representations of discourse referents*. Cambridge
studies in linguistics vol. 71. Cambridge: Cambridge university press.

Levshina, Natalia 2015. *How to do linguistics with R: Data exploration
and statistical analysis*. John Benjamins Publishing Company.

Paldanius, Hilkka 2017. Historian esseevastauksen funktionaalinen
rakenne. Teoksessa: Sirkku Latomaa, Emilia Luukka, & Niina Lilja (eds.)
*AFinLAn vuosikirja 2017*.. Suomen soveltavan kielitieteen yhdistys.

Shore, Susanna 2008. Lauseiden tekstuaalisesta jäsennyksestä.
*Virittäjä* 112:1, 24.

Vuorijärvi, Aino 2013. Tekstilaji ja yhteisö: Ammattikorkeakoulun
opinnäytetyön diskussio tekstinä.

[1] Käyttäen kirjoittajien itsensä tekemää kappaleiden ortografista
erottelua.

[2] Satunnaisotannan tekninen toteutus dokumentoitiin
git-versionhallintaan ja on nähtävillä osoitteessa x (tarkistettu
8.1.2017)

[3] Viitaamme jatkossa ryhmiin tässä esitettyjen esimerkkien numeron
perusteella.

[4] Perfektitapauksia aineistossa oli vain yksi ja sekin
konditionaalissa, joten molemmat suomen liittoaikamuodot yhdistettiin
samaan kategoriaan.

[5] viittaus githubiin

[6] Päätöksentekopuun tuottaneessa algoritmissa indikaattorin sijainti
osoittautui hieman yllättäenkin merkityksettömäksi, samoin kuin
morfologinen rakenne.
